# Generated by Django 3.0 on 2020-02-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_header',
            field=models.CharField(default='Defualt', max_length=200),
        ),
    ]
