# Generated by Django 3.0 on 2020-02-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0003_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
