# Generated by Django 3.0.3 on 2020-02-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0005_auto_20200222_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField()),
                ('comment_text', models.CharField(max_length=600)),
                ('comment_article_id', models.IntegerField()),
                ('commentor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_high_res_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
