# Generated by Django 3.0 on 2020-02-29 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0006_auto_20200225_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_article_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='article_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webblog.Article'),
            preserve_default=False,
        ),
    ]
