# Generated by Django 3.0 on 2020-02-29 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0007_auto_20200229_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 19, 35, 34, 838439)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 19, 35, 34, 838439)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(),
        ),
    ]
