# Generated by Django 3.0 on 2020-03-03 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0008_auto_20200229_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['article_date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 18, 7, 15, 768625)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 18, 7, 15, 769638)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentor_name',
            field=models.CharField(max_length=20),
        ),
    ]
