# Generated by Django 3.0 on 2020-03-03 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0013_auto_20200303_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 20, 39, 22, 63044)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 20, 39, 22, 64042)),
        ),
    ]
